### ISSUE TITLE
Uncaught TypeError: dispatch is not a function

### ISSUE THREAD

**Issue by sivanadaraja** [blueberryapps/redux-file-upload#12] opened 2016-09-14 07:19 UTC
Uncaught TypeError: dispatch is not a function
I am still getting the same error. I am using the version 0.0.13. is it fixed ?

return dispatch(fileProgress.apply(undefined, [identificator].concat(args))); -error
return dispatch(fileComplete.apply(undefined, [identificator].concat(args)));
thanks
Siva

**Comment by jakubkottnauer** [comment] 2016-09-18 16:09
Are you using redux-thunk, redux-promise-middlware or similar? If not, adding it will fix your problem. The problem is that some of the actions in this package are async and need have dispatch passed down to them.

**Comment by jrrera** [comment] 2016-10-05 01:15
I'm using redux-thunk and an experiencing the same error. I'm not well versed in React/Redux though, so I'm not sure where to start debugging. I'll post more information if I can dig deeper

**Comment by jakubkottnauer** [comment] 2016-10-05 11:12
@jrrera thanks for posting your problem. I took a look at redux-thunk and noticed that it passes dispatch on its own whereas actions in this package expect that dispatch will arrive wrapped in an object (which is something that some are middlewares do). I'll publish a fix and let you know.

**Comment by jakubkottnauer** [comment] 2016-10-05 11:54
@sivanadaraja @jrrera Your issues should be fixed in 0.0.16 🎉

**Closed as completed** 2016-10-22 11:56 UTC

**Comment by SrikanthChebrolu** [comment] 2018-02-15 20:43
Uncaught TypeError: dispatch is not a function
 I am facing the same issue
